---
language: python
python:
  - "3.6"

sudo: required

services:
  - docker

addons:
  apt:
    packages:
    - python-pip

jobs:
  include:
    - stage: "test"
      name: "Test"
      script:
        - pip install tox
        - tox -- --pg-image=postgres:alpine tests
    
    - stage: "publish"
      name: "Publish"
      if: tag IS present
      script:
        - pip install twine
        - make dist
